version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - update-type: "security"
    open-pull-requests-limit: 5
    labels:
      - "security"
