name: 📝 Submit a Blog Post
description: Submit your blog post in Markdown with frontmatter and up to 2 images
title: "[Blog] <Your Title Here>"
labels: ["blog-submission"]
body:
  - type: markdown
    attributes:
      value: |
        ## 📝 NEAR Blog Submission Requirements

        Please follow these **strict guidelines** — your post will be **automatically rejected** if it doesn’t comply:

        - ✅ Use **Markdown only** — **no raw HTML**
        - ✅ Start your post with a **frontmatter block** (see example below)
        - ✅ Include **0–2 inline images** and **one featured image** (in PNG or JPG format)
        - ✅ Subject must be one of:
          - `Community`, `Developers`, `Ecosystem`, `DAOs`, `NFTs`, `Gaming`, `Web3 Gaming`, `User-Owned AI`
        - ✅ You must include: `submission: true` in your frontmatter
        - ❌ Only one open submission per user is allowed

        ---

        🖼 **Uploading Images**

        To include images in your blog post:

        - ✅ Drag and drop them into the editor box below
        - ✅ Or paste from your clipboard (⌘+V / Ctrl+V)
        - ✅ GitHub will upload them and insert Markdown like:

          ```markdown
          ![Alt text](https://user-images.githubusercontent.com/.../image-1.png)
          ```

        ⛔ Do not upload more than **2 inline images**
        📌 Use this naming convention (with png or jpg extensions matching the image type):
        - Inline: `image-1.png`, `image-2.jpg`
        - Featured: `featured-[slug].png`

        ---

        <details>
        <summary>📌 What is frontmatter? (Click to expand)</summary>

        Frontmatter is a short block of info at the top of your post that helps categorize and publish it.

        You **must** include this in your post (keep the `---` lines):

        ```yaml
        ---
        title: "Why I Love NEAR"
        description: "Exploring what makes NEAR unique and powerful for builders"
        author: "Jane Doe"
        subject: "Community"
        featuredImage: "https://user-images.githubusercontent.com/.../featured-near.png"
        submission: true
        ---
        ```

        ✅ This should come before any headings or body content.

        </details>

  - type: textarea
    id: post
    attributes:
      label: 📄 Blog Post Content (Markdown)
      description: |
        Paste your full post here in **Markdown format**, including the frontmatter block shown above.
        Upload images into this issue and reference them like:

        ```md
        ![Example](https://user-images.githubusercontent.com/.../image-1.png)
        ```

        ❌ Raw HTML like `<img>` or `<div>` will be automatically rejected.
      placeholder: |
        ---
        title: "Why I Love NEAR"
        description: "Exploring what makes NEAR unique and powerful for builders"
        author: "Jane Doe"
        subject: "Community"
        featuredImage: "https://user-images.githubusercontent.com/.../featured-near.png"
        submission: true
        ---

        ## NEAR Is More Than Just Speed

        One thing that makes NEAR stand out...

        ![Protocol Chart](https://user-images.githubusercontent.com/.../image-protocol-chart.png)
      render: markdown
    validations:
      required: true