name: Auto-Approve & Auto-Merge Dependabot Security Fixes

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - ready_for_review

permissions:
  pull-requests: write

jobs:
  approve-and-merge:
    if: |
      github.actor == 'dependabot[bot]' &&
      contains(github.event.pull_request.labels.*.name, 'security')
    runs-on: ubuntu-latest
    steps:
      - name: Auto-approve Dependabot security PR
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge on Dependabot security PR
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
          token: ${{ secrets.GITHUB_TOKEN }}
