name: Unlock on PR rejection
on:
  pull_request:
    types: [closed]

permissions:
  issues: write

jobs:
  unlock-if-unmerged:
    if: ${{ github.event.pull_request.merged == false }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      ISSUE: ''
    steps:
      - name: Extract linked issue number from PR body
        id: parse
        run: |
          # grab the PR description
          BODY="${{ github.event.pull_request.body }}"
          echo "PR body:" >&2
          echo "$BODY" >&2

          # pull out “This blog post was submitted via [issue #NN]”
          ISSUE=$(
            grep -oE 'This blog post was submitted via \[issue #[0-9]+\]' <<< "$BODY" \
            | head -1 \
            | grep -oE '[0-9]+'
          )

          echo "Extracted ISSUE=$ISSUE" >&2
          echo "ISSUE=$ISSUE" >> $GITHUB_ENV

      - name: Log if no linked blog issue
        if: ${{ env.ISSUE == '' }}
        run: echo "No linked blog issue found; skipping unlock."

      - name: Unlock linked issue
        if: ${{ env.ISSUE != '' }}
        run: gh issue unlock ${ISSUE} --repo $GITHUB_REPOSITORY