name: Unlock on PR rejection
on:
  pull_request:
    types: [closed]

jobs:
  unlock-if-unmerged:
    if: ${{ github.event.pull_request.merged == false }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Extract linked issue number from bot comment
        id: parse
        run: |
          PR_NUM=${{ github.event.pull_request.number }}
          # fetch only the issue comments (the PR conversation)…
          COMMENTS=$(gh api \
            repos/$GITHUB_REPOSITORY/issues/$PR_NUM/comments \
            --jq '.[] | select(.user.login=="github-actions") | .body')
          # look for the “submitted via issue #NNN” line
          ISSUE=$(echo "$COMMENTS" \
            | grep -oE 'submitted via issue #[0-9]+' \
            | head -1 \
            | grep -oE '[0-9]+')
          echo "ISSUE=${ISSUE}" >> $GITHUB_ENV

      - name: Log if no linked blog issue
        if: ${{ env.ISSUE == '' }}
        run: echo "No linked blog issue found in PR body; skipping unlock."

      - name: Unlock linked issue
        if: ${{ env.ISSUE != '' }}
        run: |
          gh api repos/$GITHUB_REPOSITORY/issues/${ISSUE}/unlock