name: Validate & Import Blog Submission

on:
  issues:
    types: [opened, edited]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Validate submission
        id: validate
        run: node scripts/validate_submission.js
        env:
          GITHUB_TOKEN:      ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER:      ${{ github.event.issue.number }}
          ISSUE_BODY:        ${{ github.event.issue.body }}
          ISSUE_USER:        ${{ github.event.issue.user.login }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Import submission
        if: ${{ steps.validate.outcome == 'success' }}
        run: node scripts/import_submission.js
        env:
          GITHUB_TOKEN:      ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER:      ${{ github.event.issue.number }}
          ISSUE_BODY:        ${{ github.event.issue.body }}
          ISSUE_USER:        ${{ github.event.issue.user.login }}
          GITHUB_REPOSITORY: ${{ github.repository }}
